services:
    php-fpm:
        build:
            args:
                user: app-user
                uid: 1000
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        container_name: app-php-fpm
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: app-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "${HOST_DB_PORT}:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:1.27.2-alpine
        container_name: app-nginx
        restart: unless-stopped
        ports:
            - "${HOST_NGINX_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network

    node:
        build:
            context: ./
            dockerfile: docker/node/Dockerfile
        container_name: app-node
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - "5173:5173"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules:
